---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "200.200.200.251"
    vcenter_username: "administrator@vsphere.kh"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    iac_template: "Temp-IaC"

  tasks:
  - name: Deploy IaC VM from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.student_id + '-IaC' }}"
      state: "poweredon"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ 'JMT/' + item.student_id }}"
      esxi_hostname: '{{ item.esxi }}'
      datastore: "{{ item.datastore }}"
      template: "{{ iac_template }}"
    with_items:
    - { student_id: JMT05, esxi: 200.200.200.247 , datastore: Local-02 }   
    delegate_to: localhost
 
